const ICONS = {focus:'i-headphones',reset:'i-spark',winddown:'i-sun',sleep:'i-moon',wake:'i-sun'};
const KINDS = {
  focus:{label:'Focus',subtitle:'Room to find your concentration',color:'#b9d8c3',bg:'#8ec6a12d',glow:'#8fc8a3',zoneMinutes:180,delayMinutes:20,gapMinutes:35,repeat:true,volume:42,stages:[{sound:'brown',minutes:18,fade:8},{sound:'pink',minutes:12,fade:10}]},
  reset:{label:'Reset',subtitle:'Small moments to begin again',color:'#c9c1ef',bg:'#ad9de63a',glow:'#b6a4ed',zoneMinutes:120,delayMinutes:25,gapMinutes:35,repeat:true,volume:38,stages:[{sound:'rain',minutes:3,fade:5},{sound:'ocean',minutes:4,fade:5}]},
  winddown:{label:'Wind-down',subtitle:'Let the evening soften',color:'#efd4a2',bg:'#e6ad6630',glow:'#e7b377',zoneMinutes:120,delayMinutes:10,gapMinutes:30,repeat:true,volume:35,stages:[{sound:'ocean',minutes:10,fade:10},{sound:'pink',minutes:10,fade:12}]},
  sleep:{label:'Sleep',subtitle:'Ease slowly toward rest',color:'#b1c5e7',bg:'#8ea9dd2f',glow:'#86a8e0',zoneMinutes:90,delayMinutes:0,gapMinutes:30,repeat:false,volume:32,stages:[{sound:'pink',minutes:15,fade:10},{sound:'ocean',minutes:15,fade:15},{sound:'brown',minutes:15,fade:15}]},
  wake:{label:'Wake',subtitle:'A gentler start',color:'#efd4a2',bg:'#e6ad6630',glow:'#e7b377',zoneMinutes:45,delayMinutes:0,gapMinutes:20,repeat:false,volume:45,stages:[{sound:'ocean',minutes:4,fade:10},{sound:'pink',minutes:4,fade:10},{sound:'rain',minutes:4,fade:10}]}
};
const QUICK_KINDS=['focus','reset','winddown','sleep'];
const BUILTIN_SOUNDS=[
  {id:'brown',name:'Brown noise',type:'noise',symbol:'◒',description:'Deep, warm and steady',color:'#e8c9a6',bg:'#dd9c6330'},
  {id:'pink',name:'Pink noise',type:'noise',symbol:'◐',description:'Soft and balanced',color:'#e6bec3',bg:'#de8e9c30'},
  {id:'white',name:'White noise',type:'noise',symbol:'◉',description:'Bright and consistent',color:'#d3deec',bg:'#a3bcda2b'},
  {id:'rain',name:'Soft rain',type:'nature',symbol:'☂',description:'A gentle passing shower',color:'#a9cadb',bg:'#86b8d633'},
  {id:'ocean',name:'Ocean hush',type:'nature',symbol:'≈',description:'Slow and spacious waves',color:'#a8d8ca',bg:'#74c0aa30'},
  {id:'tone432',name:'432 Hz tone',type:'tone',symbol:'♪',description:'A soft, grounding tone',color:'#d8c6ed',bg:'#b398d937'},
  {id:'tone528',name:'528 Hz tone',type:'tone',symbol:'♫',description:'A clear, gentle tone',color:'#e7d5a9',bg:'#d6b87535'}
];
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const escapeHTML=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const readJSON=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const saveJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
const icon=name=>`<svg aria-hidden="true"><use href="#${name}"/></svg>`;
const kindStyle=kind=>{const k=KINDS[kind]||KINDS.reset;return `--icon-color:${k.color};--icon-bg:${k.bg};--glow:${k.glow}`};
const soundStyle=sound=>`--icon-color:${sound.color||'#d7dfba'};--icon-bg:${sound.bg||'#9cba9c30'}`;
const soundName=id=>sounds.find(sound=>sound.id===id)?.name||'Missing sound';
const formatClock=seconds=>`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`;
const formatDuration=minutes=>minutes<60?`${minutes} min`:minutes%60?`${Math.floor(minutes/60)} hr ${minutes%60} min`:`${minutes/60} hr`;
const timeUntil=timestamp=>{const seconds=Math.max(0,Math.ceil((timestamp-Date.now())/1000));return seconds>=3600?`${Math.floor(seconds/3600)}h ${Math.ceil(seconds%3600/60)}m`:seconds>=60?`${Math.ceil(seconds/60)} min`:`${seconds} sec`};
const clone=value=>structuredClone(value);
const makeDefault=kind=>({id:uid(),name:`${KINDS[kind].label} Zone`,kind,...clone(KINDS[kind])});
function migrateRoutines(){const old=readJSON('hushday-routines-v1',null);if(!Array.isArray(old))return QUICK_KINDS.map(makeDefault);const converted=old.map(item=>{const kind=KINDS[item.kind]?item.kind:'focus',base=makeDefault(kind),oldSounds=Array.isArray(item.sounds)&&item.sounds.length?item.sounds:base.stages.map(stage=>stage.sound);return {...base,id:item.id||uid(),name:item.name||base.name,volume:Number(item.volume)||base.volume,stages:oldSounds.map(sound=>({sound,minutes:Math.max(1,Math.round((Number(item.duration)||20)/oldSounds.length)),fade:5}))}});if(!converted.some(item=>item.kind==='winddown'))converted.push(makeDefault('winddown'));return converted}
let routines=readJSON('hushday-zones-v2',null);if(!Array.isArray(routines)){routines=migrateRoutines();saveJSON('hushday-zones-v2',routines)}
let history=readJSON('hushday-history-v1',[]);
let activeZone=readJSON('hushday-active-zone-v2',null);
if(activeZone){if(activeZone.endsAt<=Date.now()){activeZone=null;saveJSON('hushday-active-zone-v2',null)}else if(['playing','starting'].includes(activeZone.phase)){activeZone.phase='waiting';activeZone.nextCycleAt=Date.now();saveJSON('hushday-active-zone-v2',activeZone)}}
let sounds=[...BUILTIN_SOUNDS],soundFiles=[],draftStages=[],toastTimeout;

function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.classList.remove('show'),3500)}
function saveRoutines(){saveJSON('hushday-zones-v2',routines);renderQuick();renderTodayRoutines();renderRoutines()}
function saveZone(){saveJSON('hushday-active-zone-v2',activeZone);renderZone();renderRoutines()}
function showView(view){$$('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}-view`));$$('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('#view-name').textContent={today:'TODAY',routines:'MY ZONES',sounds:'SOUND LIBRARY',insights:'MY PATTERNS'}[view]||'TODAY';window.scrollTo({top:0,behavior:'smooth'});if(view==='insights')renderInsights()}

class SoundEngine {
  constructor(){this.context=null;this.master=null;this.current=null;this.session=null;this.timer=null;this.bufferCache={};this.importBufferCache={};this.armed=false;this.settings=readJSON('hushday-sound-settings-v1',{brightness:50,depth:50,movement:25,width:35})}
  async ensure(){if(!this.context){this.context=new (window.AudioContext||window.webkitAudioContext)();this.master=this.context.createGain();this.master.gain.value=.55;this.master.connect(this.context.destination)}if(this.context.state==='suspended')await this.context.resume();this.armed=this.context.state==='running';updateArmStatus();return this.armed}
  noiseBuffer(type){if(this.bufferCache[type])return this.bufferCache[type];const ctx=this.context,length=ctx.sampleRate*8,buffer=ctx.createBuffer(2,length,ctx.sampleRate);for(let ch=0;ch<2;ch++){let brown=0,b0=0,b1=0,b2=0,b3=0,b4=0,b5=0,b6=0;const data=buffer.getChannelData(ch);for(let i=0;i<length;i++){const white=Math.random()*2-1;let value;if(type==='brown'||type==='ocean'){brown=(brown+.02*white)/1.02;value=brown*3.5}else if(type==='pink'){b0=.99886*b0+white*.0555179;b1=.99332*b1+white*.0750759;b2=.969*b2+white*.153852;b3=.8665*b3+white*.3104856;b4=.55*b4+white*.5329522;b5=-.7616*b5-white*.016898;value=(b0+b1+b2+b3+b4+b5+b6+white*.5362)*.11;b6=white*.115926}else value=white*.23;data[i]=Math.max(-1,Math.min(1,value))}}this.bufferCache[type]=buffer;return buffer}
  async sourceFor(id){await this.ensure();const ctx=this.context,sound=sounds.find(item=>item.id===id);if(!sound)throw new Error('A cycle sound is unavailable');const input=ctx.createGain(),filter=ctx.createBiquadFilter(),pan=ctx.createStereoPanner(),gain=ctx.createGain();gain.gain.value=0;input.connect(filter).connect(pan).connect(gain).connect(this.master);let node,cleanup=()=>{};
    if(sound.type==='file'){const file=soundFiles.find(item=>item.id===id)?.file;if(!file)throw new Error('Imported file unavailable');if(!this.importBufferCache[id])this.importBufferCache[id]=await ctx.decodeAudioData(await file.arrayBuffer());node=ctx.createBufferSource();node.buffer=this.importBufferCache[id];node.loop=true;node.connect(input);node.start()}
    else if(sound.type==='tone'){node=ctx.createOscillator();node.type='sine';node.frequency.value=id==='tone528'?528:432;node.connect(input);node.start();input.gain.value=.12}
    else{node=ctx.createBufferSource();node.buffer=this.noiseBuffer(sound.type==='nature'?(id==='ocean'?'ocean':'white'):id);node.loop=true;node.connect(input);node.start()}
    const voice={id,node,input,filter,pan,gain,cleanup,sound};this.applyVoiceSettings(voice);return voice}
  applyVoiceSettings(voice){const {sound,filter}=voice;filter.type=sound.id==='rain'?'highpass':'lowpass';filter.frequency.value=sound.id==='rain'?250+this.settings.brightness*13:Math.max(180,450+this.settings.brightness*95-this.settings.depth*38);filter.Q.value=.15+this.settings.depth/180}
  release(voice,seconds=2){if(!voice)return;const t=this.context.currentTime;voice.gain.gain.cancelScheduledValues(t);voice.gain.gain.setValueAtTime(voice.gain.gain.value,t);voice.gain.gain.linearRampToValueAtTime(0,t+seconds);setTimeout(()=>{try{voice.node.stop?.()}catch{}voice.cleanup();voice.input.disconnect();voice.filter.disconnect();voice.pan.disconnect();voice.gain.disconnect()},(seconds+.2)*1000)}
  async switchSound(id,fade=2){const next=await this.sourceFor(id),t=this.context.currentTime;next.gain.gain.setValueAtTime(0,t);next.gain.gain.linearRampToValueAtTime(.85,t+Math.max(0.02,fade));this.release(this.current,fade);this.current=next;renderPlayer()}
  async start(config,onComplete=null){try{await this.ensure();this.stop(false);const stages=config.stages.filter(stage=>sounds.some(sound=>sound.id===stage.sound));if(!stages.length)throw new Error('Choose a sound for this cycle');const boundaries=[];let duration=0;for(const stage of stages){duration+=Number(stage.minutes)*60;boundaries.push(duration)}this.session={name:config.name,kind:config.kind||'focus',stages,boundaries,duration,volume:Number(config.volume)||40,elapsed:0,step:0,startedAt:Date.now(),paused:false,onComplete};this.master.gain.value=this.session.volume/100;await this.switchSound(stages[0].sound,Number(stages[0].fade)||0);history.unshift({name:config.name,kind:config.kind||'focus',time:new Date().toISOString(),duration:Math.round(duration/60),sound:stages[0].sound});history=history.slice(0,100);saveJSON('hushday-history-v1',history);this.timer=setInterval(()=>this.tick(),250);renderPlayer();return true}catch(error){this.stop(false);toast(error.message||'Unable to start audio');return false}}
  tick(){const s=this.session;if(!s||s.paused)return;s.elapsed=(Date.now()-s.startedAt)/1000;if(s.elapsed>=s.duration){const callback=s.onComplete;this.stop();callback?.();toast('Your sound cycle is complete');return}const step=s.boundaries.findIndex(end=>s.elapsed<end);if(step!==s.step&&step>=0){s.step=step;this.switchSound(s.stages[step].sound,Number(s.stages[step].fade)||0).catch(()=>this.stop())}if(this.current){this.current.pan.pan.value=Math.sin(s.elapsed*.18)*(this.settings.movement/100)*(this.settings.width/100);if(this.current.id==='ocean')this.current.input.gain.value=.55+.35*(1+Math.sin(s.elapsed*.25))/2;const finalFade=Math.max(1,Number(s.stages.at(-1).fade)||1),remaining=s.duration-s.elapsed;let envelope=Math.min(1,remaining/finalFade);if(s.kind==='sleep')envelope=Math.min(envelope,remaining/120);this.master.gain.value=Math.max(0,envelope)*s.volume/100}updateProgress()}
  pause(){const s=this.session;if(!s)return;if(s.paused){this.context.resume();s.startedAt=Date.now()-s.elapsed*1000;s.paused=false}else{s.elapsed=(Date.now()-s.startedAt)/1000;this.context.suspend();s.paused=true}renderPlayer()}
  skip(){const s=this.session;if(!s)return;const next=(s.step+1)%s.stages.length;s.step=next;s.elapsed=next? s.boundaries[next-1]:0;s.startedAt=Date.now()-s.elapsed*1000;this.switchSound(s.stages[next].sound,Number(s.stages[next].fade)||0).catch(()=>this.stop());renderPlayer()}
  stop(render=true){clearInterval(this.timer);this.timer=null;if(this.context?.state==='suspended')this.context.resume().catch(()=>{});if(this.current){this.release(this.current,.5);this.current=null}this.session=null;if(render)renderPlayer()}
}
const engine=new SoundEngine();

function renderQuick(){$('#quick-grid').innerHTML=QUICK_KINDS.map(kind=>{const template=routines.find(item=>item.kind===kind)||makeDefault(kind),k=KINDS[kind];return `<button class="quick-card" data-zone-kind="${kind}" style="${kindStyle(kind)}"><span class="quick-icon">${icon(ICONS[kind])}</span><strong>${k.label} Zone</strong><small>Next ${formatDuration(template.zoneMinutes)} · starts in ${template.delayMinutes} min</small></button>`}).join('')}
function renderTodayRoutines(){$('#today-routines').innerHTML=routines.length?routines.map(r=>`<div class="schedule-item" style="${kindStyle(r.kind)}"><span class="schedule-time">${formatDuration(r.zoneMinutes)}</span><span class="schedule-icon">${icon(ICONS[r.kind]||ICONS.focus)}</span><span class="schedule-info"><strong>${escapeHTML(r.name)}</strong><small>${r.stages.map(stage=>soundName(stage.sound)).join(' → ')} · first sound in ${r.delayMinutes} min</small></span><button class="schedule-action" data-activate-id="${r.id}" aria-label="Turn on ${escapeHTML(r.name)}">${icon('i-play')}</button></div>`).join(''):'<div class="empty-state">Create a zone to start shaping your sound.</div>'}
function renderRoutines(){$('#routine-list').innerHTML=routines.length?routines.map(r=>`<article class="routine-card" style="${kindStyle(r.kind)}"><span class="schedule-icon">${icon(ICONS[r.kind]||ICONS.focus)}</span><div><h3>${escapeHTML(r.name)}${activeZone?.routineId===r.id?'<span class="routine-live">ON</span>':''}</h3><div class="routine-meta"><span>${formatDuration(r.zoneMinutes)} zone</span><span>wait ${r.delayMinutes} min</span><span>${r.stages.reduce((sum,stage)=>sum+Number(stage.minutes),0)} min cycle</span><span>${r.repeat?`repeat after ${r.gapMinutes} min`:'play once'}</span></div><div class="routine-journey">${r.stages.map(stage=>`${escapeHTML(soundName(stage.sound))} ${stage.minutes}m`).join(' → ')}</div></div><div class="routine-actions"><button class="small-btn" data-activate-id="${r.id}">${icon('i-play')} Turn on</button><button class="small-btn" data-edit-id="${r.id}">Edit</button><button class="icon-btn" data-delete-id="${r.id}" aria-label="Delete ${escapeHTML(r.name)}">${icon('i-trash')}</button></div></article>`).join(''):'<div class="empty-state">No zones saved yet. Create your first one above.</div>'}
function renderZone(){const el=$('#active-zone-card');if(!activeZone){el.classList.remove('active');el.innerHTML=`<div class="zone-empty-mark">✳</div><div><strong>No zone is on right now</strong><p>Open one below whenever sounds would be welcome.</p></div>`;return}el.classList.add('active');const r=activeZone.routine,phase=activeZone.phase;let message;if(!engine.armed)message='Audio is paused in this page. Enable it to continue.';else if(phase==='playing')message=`Cycle ${activeZone.cyclesPlayed+1} is playing · ${soundName(engine.session?.stages[engine.session.step]?.sound||r.stages[0].sound)}`;else if(phase==='starting')message='Your sound cycle is starting…';else if(phase==='complete')message='The cycle has finished. Sound stays quiet until you turn this zone off.';else message=`Your next cycle begins in ${timeUntil(activeZone.nextCycleAt)}.`;el.innerHTML=`<div class="zone-status-top"><span class="zone-on-dot"></span><span>ZONE ON</span><span class="zone-remaining" id="zone-remaining">${timeUntil(activeZone.endsAt)} left</span></div><h3>${escapeHTML(r.name)}</h3><p id="zone-message">${escapeHTML(message)}</p><div class="zone-progress"><span style="width:${Math.min(100,Math.max(0,(Date.now()-activeZone.startedAt)/(activeZone.endsAt-activeZone.startedAt)*100))}%"></span></div><div class="zone-footer"><span>Ends ${new Date(activeZone.endsAt).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</span><div>${!engine.armed?'<button class="small-btn" id="resume-zone-audio">Enable audio</button>':''}<button class="small-btn" data-zone-now>${phase==='playing'?'Restart cycle':'Play cycle now'}</button><button class="zone-off" data-zone-off>Turn off</button></div></div>`}
function renderLibrary(){const term=$('#sound-search').value.trim().toLowerCase();const filtered=sounds.filter(sound=>`${sound.name} ${sound.description}`.toLowerCase().includes(term));$('#sound-library').innerHTML=filtered.map(sound=>`<article class="sound-card" style="${soundStyle(sound)}"><div class="sound-card-head"><span class="sound-symbol">${escapeHTML(sound.symbol)}</span><button class="sound-play" data-preview-id="${sound.id}" aria-label="Play ${escapeHTML(sound.name)}">${icon('i-play')}</button></div><h3>${escapeHTML(sound.name)}</h3><p>${escapeHTML(sound.description)}</p></article>`).join('')||'<div class="empty-state">No sounds match your search.</div>'}
function renderInsights(){const total=history.length,minutes=history.reduce((sum,item)=>sum+(Number(item.duration)||0),0),counts={};history.forEach(item=>counts[item.sound]=(counts[item.sound]||0)+1);const favorite=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0];$('#insights-content').innerHTML=`<div class="insight-grid"><div class="stat-card"><span class="tiny-label">CYCLES STARTED</span><strong>${total}</strong><small>moments made for yourself</small></div><div class="stat-card"><span class="tiny-label">CYCLE TIME</span><strong>${minutes<60?minutes+'m':(minutes/60).toFixed(1)+'h'}</strong><small>sound time chosen</small></div><div class="stat-card"><span class="tiny-label">MOST CHOSEN SOUND</span><strong style="font-size:${favorite?'25':'38'}px">${favorite?escapeHTML(soundName(favorite)):'—'}</strong><small>${favorite?'based on cycles started':'your favorite will appear here'}</small></div></div><div class="history-card"><h2>Recent listening</h2>${history.length?history.slice(0,8).map(item=>`<div class="history-row"><span>${escapeHTML(item.name)}</span><span>${new Date(item.time).toLocaleDateString('en-US',{month:'short',day:'numeric'})} · ${item.duration} min</span></div>`).join(''):'<p class="history-empty">Start a sound cycle and your listening pattern will appear here.</p>'}</div>`}
function renderPlayer(){const card=$('#player-card'),s=engine.session;card.classList.toggle('is-playing',!!s&&!s.paused);card.innerHTML=`<div class="player-overline">${s?'NOW PLAYING':'READY WHEN YOU ARE'}</div><div class="sound-orb"><div class="orb-ring"></div><div class="orb-ring"></div><div class="orb-core"></div></div><h2 class="player-title">${s?escapeHTML(s.name):'A moment of quiet'}</h2><p class="player-subtitle">${s?escapeHTML(soundName(s.stages[s.step].sound))+' · stage '+(s.step+1)+' of '+s.stages.length:'Turn on a zone and let the sound come to you'}</p><div class="progress-track"><div class="progress-fill" id="progress-fill"></div></div><div class="progress-labels"><span id="elapsed-label">${s?formatClock(s.elapsed):'0:00'}</span><span>${s?formatClock(s.duration):'0:00'}</span></div><div class="player-controls"><button class="player-control-secondary" id="stop-session" aria-label="Stop sound" ${s?'':'disabled'}>${icon('i-x')}</button><button class="play-button" id="toggle-play" aria-label="${s?(s.paused?'Resume':'Pause'):'Start focus cycle'}">${icon(s&&!s.paused?'i-pause':'i-play')}</button><button class="player-control-secondary" id="skip-sound" aria-label="Next stage" ${s&&s.stages.length>1?'':'disabled'}>${icon('i-arrow')}</button></div>`;updateProgress()}
function updateProgress(){const s=engine.session;if(!s)return;const fill=$('#progress-fill'),label=$('#elapsed-label');if(fill)fill.style.width=`${Math.min(100,s.elapsed/s.duration*100)}%`;if(label)label.textContent=formatClock(s.elapsed)}

function renderStages(){const list=$('#stage-list');list.innerHTML=draftStages.map((stage,index)=>`<div class="stage-row" data-stage-index="${index}"><span class="stage-number">${String(index+1).padStart(2,'0')}</span><div class="stage-fields"><label>Sound<select data-stage-sound>${sounds.map(sound=>`<option value="${sound.id}" ${stage.sound===sound.id?'selected':''}>${escapeHTML(sound.name)}</option>`).join('')}</select></label><label>Length<div class="input-unit"><input data-stage-minutes type="number" min="1" max="240" value="${stage.minutes}"><span>min</span></div></label><label>Fade<div class="input-unit"><input data-stage-fade type="number" min="0" max="60" value="${stage.fade}"><span>sec</span></div></label></div><div class="stage-actions"><button type="button" class="stage-move" data-stage-up aria-label="Move stage ${index+1} up" ${index===0?'disabled':''}>↑</button><button type="button" class="stage-move" data-stage-down aria-label="Move stage ${index+1} down" ${index===draftStages.length-1?'disabled':''}>↓</button><button type="button" class="stage-move" data-stage-remove aria-label="Remove stage ${index+1}" ${draftStages.length===1?'disabled':''}>×</button></div></div>`).join('');renderCycleSummary()}
function renderCycleSummary(){const form=$('#routine-form'),minutes=draftStages.reduce((sum,stage)=>sum+(Number(stage.minutes)||0),0),zoneMinutes=Number(form.elements.zoneMinutes.value)||180,delay=Number(form.elements.delayMinutes.value)||0;$('#cycle-summary').innerHTML=`<strong>${minutes} min cycle</strong><span>${draftStages.length} stage${draftStages.length===1?'':'s'} · ${form.elements.repeat.checked?'repeats during the zone':'plays once'}</span>${delay+minutes>zoneMinutes?'<small>The zone may end before the first cycle finishes.</small>':''}`}
function openRoutine(id){const r=routines.find(item=>item.id===id),form=$('#routine-form'),base=r||makeDefault('focus');form.reset();form.elements.id.value=r?.id||'';form.elements.name.value=r?.name||'';form.elements.kind.value=base.kind;form.elements.zoneMinutes.value=String(base.zoneMinutes);form.elements.delayMinutes.value=base.delayMinutes;form.elements.gapMinutes.value=base.gapMinutes;form.elements.repeat.checked=base.repeat;form.elements.volume.value=base.volume;draftStages=clone(base.stages);$('#volume-value').textContent=`${base.volume}%`;$('#dialog-title').textContent=r?'Edit zone':'Create a zone';updateRepeatField();renderStages();$('#routine-dialog').showModal()}
function closeRoutine(){$('#routine-dialog').close()}
function updateRepeatField(){$('#repeat-gap').disabled=!$('#routine-form').elements.repeat.checked;renderCycleSummary()}
function saveRoutine(event){event.preventDefault();const form=event.currentTarget,data=new FormData(form),id=String(data.get('id'))||uid(),name=String(data.get('name')).trim(),kind=String(data.get('kind')),zoneMinutes=Number(data.get('zoneMinutes')),delayMinutes=Number(data.get('delayMinutes')),gapMinutes=Number(form.elements.gapMinutes.value),volume=Number(data.get('volume'));if(!name||!KINDS[kind]||!Number.isFinite(zoneMinutes)||zoneMinutes<10||zoneMinutes>720||!Number.isFinite(delayMinutes)||delayMinutes<0||delayMinutes>240||!Number.isFinite(gapMinutes)||gapMinutes<0||gapMinutes>240||!Number.isFinite(volume)||volume<5||volume>100){toast('Check the zone details');return}const stages=draftStages.map(stage=>({sound:stage.sound,minutes:Number(stage.minutes),fade:Number(stage.fade)}));if(!stages.length||stages.some(stage=>!sounds.some(sound=>sound.id===stage.sound)||!Number.isFinite(stage.minutes)||stage.minutes<1||stage.minutes>240||!Number.isFinite(stage.fade)||stage.fade<0||stage.fade>60)){toast('Check each cycle stage');return}const next={id,name,kind,zoneMinutes,delayMinutes,gapMinutes,repeat:form.elements.repeat.checked,volume,stages};const index=routines.findIndex(item=>item.id===id);if(index>=0)routines[index]=next;else routines.push(next);saveRoutines();closeRoutine();toast(index>=0?'Zone updated. Changes apply next time it starts.':'Zone created')}

function openDatabase(){return new Promise((resolve,reject)=>{const request=indexedDB.open('hushday-audio-v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('files',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function loadFiles(){try{const db=await openDatabase();soundFiles=await new Promise((resolve,reject)=>{const tx=db.transaction('files','readonly'),request=tx.objectStore('files').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});sounds=[...BUILTIN_SOUNDS,...soundFiles.map(file=>({id:file.id,name:file.name,type:'file',symbol:'♫',description:'Your imported audio',color:'#d1dcb4',bg:'#bbca9433'}))];renderLibrary();if($('#routine-dialog').open)renderStages()}catch{toast('Imported audio storage is unavailable in this browser')}}
async function importFile(file){if(!file)return;if(!file.type.startsWith('audio/')){toast('Choose an audio file');return}if(file.size>50*1024*1024){toast('Choose an audio file under 50 MB');return}try{const db=await openDatabase(),item={id:`file-${uid()}`,name:file.name.replace(/\.[^.]+$/,'').slice(0,42),file};await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(item);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});await loadFiles();toast(`${item.name} added to your library`)}catch{toast('Unable to save this audio file')}}

function updateArmStatus(){const label=$('#audio-arm-status'),button=$('#arm-audio');if(!label||!button)return;label.textContent=engine.armed?'Audio is enabled for this page':'Audio needs to be enabled in this page';button.textContent=engine.armed?'Audio enabled':'Enable audio';button.disabled=engine.armed;renderZone()}
async function activateZone(routine){try{await engine.ensure();engine.stop();const now=Date.now();activeZone={routineId:routine.id,routine:clone(routine),startedAt:now,endsAt:now+routine.zoneMinutes*60000,nextCycleAt:now+routine.delayMinutes*60000,cyclesPlayed:0,phase:'waiting'};saveZone();zoneTick();toast(`${routine.name} is on for ${formatDuration(routine.zoneMinutes)}`)}catch{toast('This browser could not enable audio')}}
function deactivateZone(ended=false){if(activeZone?.phase==='playing'||activeZone?.phase==='starting')engine.stop();activeZone=null;saveZone();if(ended)toast('Your zone has ended');else toast('Zone turned off')}
function finishZoneCycle(interrupted=false){if(!activeZone||!['playing','starting'].includes(activeZone.phase))return;if(!interrupted)activeZone.cyclesPlayed++;const next=Date.now()+activeZone.routine.gapMinutes*60000;activeZone.phase=activeZone.routine.repeat&&next<activeZone.endsAt?'waiting':'complete';activeZone.nextCycleAt=next;saveZone()}
function zoneTick(){if(!activeZone)return;const now=Date.now();if(now>=activeZone.endsAt){deactivateZone(true);return}if(activeZone.phase==='playing'&&!engine.session){finishZoneCycle(true);return}if(activeZone.phase==='waiting'&&now>=activeZone.nextCycleAt&&engine.armed&&!engine.session){activeZone.phase='starting';saveZone();const routine=activeZone.routine,startedAt=activeZone.startedAt;engine.start(routine,finishZoneCycle).then(success=>{if(!activeZone||activeZone.startedAt!==startedAt){if(success)engine.stop();return}if(success){activeZone.phase='playing';saveZone();toast(`${routine.name} cycle is playing`)}else{activeZone.phase='waiting';activeZone.nextCycleAt=Date.now()+60000;saveZone()}});return}renderZone()}
function cycleNow(){if(!activeZone)return;engine.stop();activeZone.phase='waiting';activeZone.nextCycleAt=Date.now();saveZone();zoneTick()}
function startManual(config){if(activeZone&&['playing','starting'].includes(activeZone.phase))finishZoneCycle(true);engine.start(config)}

document.addEventListener('click',event=>{const view=event.target.closest('[data-view]');if(view){showView(view.dataset.view);return}const quick=event.target.closest('[data-zone-kind]');if(quick){const kind=quick.dataset.zoneKind;activateZone(routines.find(item=>item.kind===kind)||makeDefault(kind));return}const activate=event.target.closest('[data-activate-id]');if(activate){const routine=routines.find(item=>item.id===activate.dataset.activateId);if(routine)activateZone(routine);return}const edit=event.target.closest('[data-edit-id]');if(edit){openRoutine(edit.dataset.editId);return}const remove=event.target.closest('[data-delete-id]');if(remove){const routine=routines.find(item=>item.id===remove.dataset.deleteId);if(routine&&confirm(`Delete ${routine.name}?`)){routines=routines.filter(item=>item.id!==routine.id);saveRoutines();toast('Zone deleted')}return}const preview=event.target.closest('[data-preview-id]');if(preview){const sound=sounds.find(item=>item.id===preview.dataset.previewId);startManual({name:sound.name,kind:'reset',stages:[{sound:sound.id,minutes:5,fade:2}],volume:40});return}if(event.target.closest('[data-zone-off]')){deactivateZone();return}if(event.target.closest('[data-zone-now]')){cycleNow();return}if(event.target.closest('#resume-zone-audio')){engine.ensure().then(zoneTick);return}const stageButton=event.target.closest('[data-stage-up],[data-stage-down],[data-stage-remove]');if(stageButton){const index=Number(stageButton.closest('[data-stage-index]').dataset.stageIndex);if(stageButton.hasAttribute('data-stage-remove'))draftStages.splice(index,1);else{const other=index+(stageButton.hasAttribute('data-stage-up')?-1:1);[draftStages[index],draftStages[other]]=[draftStages[other],draftStages[index]]}renderStages()}});
$('#new-routine-top').addEventListener('click',()=>openRoutine());$('#new-routine-page').addEventListener('click',()=>openRoutine());$('#arm-audio').addEventListener('click',async()=>{try{await engine.ensure();zoneTick();toast('Audio is ready for this page')}catch{toast('This browser could not enable audio')}});$('#close-dialog').addEventListener('click',closeRoutine);$('#cancel-dialog').addEventListener('click',closeRoutine);$('#routine-form').addEventListener('submit',saveRoutine);$('#routine-volume').addEventListener('input',event=>$('#volume-value').textContent=`${event.target.value}%`);$('#routine-kind').addEventListener('change',event=>{if(!$('#routine-form').elements.id.value){const base=KINDS[event.target.value],form=$('#routine-form');form.elements.zoneMinutes.value=base.zoneMinutes;form.elements.delayMinutes.value=base.delayMinutes;form.elements.gapMinutes.value=base.gapMinutes;form.elements.repeat.checked=base.repeat;form.elements.volume.value=base.volume;$('#volume-value').textContent=`${base.volume}%`;draftStages=clone(base.stages);updateRepeatField();renderStages()}});$('#routine-form').addEventListener('input',renderCycleSummary);$('#routine-form').elements.repeat.addEventListener('change',updateRepeatField);$('#add-stage').addEventListener('click',()=>{draftStages.push({sound:'brown',minutes:5,fade:5});renderStages()});$('#stage-list').addEventListener('input',event=>{const row=event.target.closest('[data-stage-index]');if(!row)return;const stage=draftStages[Number(row.dataset.stageIndex)];if(event.target.matches('[data-stage-sound]'))stage.sound=event.target.value;if(event.target.matches('[data-stage-minutes]'))stage.minutes=Number(event.target.value);if(event.target.matches('[data-stage-fade]'))stage.fade=Number(event.target.value);renderCycleSummary()});$('#sound-search').addEventListener('input',renderLibrary);$('#import-audio').addEventListener('click',()=>$('#audio-file').click());$('#audio-file').addEventListener('change',event=>{importFile(event.target.files[0]);event.target.value=''});$('#player-card').addEventListener('click',event=>{if(event.target.closest('#toggle-play')){if(engine.session)engine.pause();else{const routine=routines.find(item=>item.kind==='focus')||makeDefault('focus');startManual(routine)}}else if(event.target.closest('#stop-session')){engine.stop();if(activeZone?.phase==='playing')finishZoneCycle(true)}else if(event.target.closest('#skip-sound'))engine.skip()});$('#routine-dialog').addEventListener('click',event=>{if(event.target===$('#routine-dialog'))closeRoutine()});$$('[data-sound-setting]').forEach(input=>{input.value=engine.settings[input.dataset.soundSetting];input.addEventListener('input',()=>{engine.settings[input.dataset.soundSetting]=Number(input.value);saveJSON('hushday-sound-settings-v1',engine.settings);if(engine.current)engine.applyVoiceSettings(engine.current)})});

$('#today-date').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});renderQuick();renderTodayRoutines();renderRoutines();renderLibrary();renderPlayer();renderZone();updateArmStatus();loadFiles();zoneTick();setInterval(zoneTick,1000);
