// Generated by scripts/blend-lab/measure.mjs. Do not edit by hand.
//
// Auto-Blend v1 per-version measurements, frozen: a saved Mix with blend v1 must always plan the same,
// so a later re-measure goes into a new table for a new rule version rather than editing this one.
// lufs: integrated loudness at the default level (ITU-R BS.1770), lowShare: share of energy below 150 Hz.

export interface VersionData { lufs: number; lowShare: number }

export const SOUND_DATA_V1: Record<string, VersionData> = {
  'brown': { lufs: -22.14, lowShare: 0.439 },
  'red': { lufs: -23.32, lowShare: 0.674 },
  'pink': { lufs: -22.3, lowShare: 0.262 },
  'white': { lufs: -31.36, lowShare: 0.005 },
  'tone432': { lufs: -29.15, lowShare: 0 },
  'tone432.a': { lufs: -29.15, lowShare: 0 },
  'tone528': { lufs: -29.69, lowShare: 0 },
  'tone528.a': { lufs: -29.69, lowShare: 0 },
  'fan': { lufs: -22.77, lowShare: 0.54 },
  'fan.a': { lufs: -22.79, lowShare: 0.452 },
  'fan.b': { lufs: -22.74, lowShare: 0.762 },
  'rain': { lufs: -23.17, lowShare: 0.002 },
  'rain.a': { lufs: -23.08, lowShare: 0.087 },
  'rain.b': { lufs: -23.15, lowShare: 0.015 },
  'ocean': { lufs: -23.66, lowShare: 0.112 },
  'ocean.a': { lufs: -23.72, lowShare: 0.046 },
  'ocean.b': { lufs: -23.71, lowShare: 0.136 },
  'wind': { lufs: -25.7, lowShare: 0.204 },
  'wind.a': { lufs: -25.61, lowShare: 0.397 },
  'wind.b': { lufs: -25.7, lowShare: 0.037 },
  'stream': { lufs: -25.3, lowShare: 0.544 },
  'stream.a': { lufs: -25.23, lowShare: 0.032 },
  'stream.b': { lufs: -25.19, lowShare: 0.042 },
  'fire': { lufs: -23.74, lowShare: 0.69 },
  'fire.a': { lufs: -23.61, lowShare: 0.531 },
  'fire.b': { lufs: -23.5, lowShare: 0.727 },
  'night': { lufs: -27.56, lowShare: 0.068 },
  'night.a': { lufs: -27.66, lowShare: 0 },
  'night.b': { lufs: -27.57, lowShare: 0.006 },
  'focus': { lufs: -23.09, lowShare: 0.64 },
  'focus.a': { lufs: -23.04, lowShare: 0.932 },
  'focus.b': { lufs: -23.04, lowShare: 0.713 },
};
