// Generated by scripts/blend-lab/measure.mjs. Do not edit by hand.
//
// Auto-Blend v1 per-version measurements, frozen: a saved Mix with blend v1 must always plan the same,
// so a later re-measure goes into a new table for a new rule version rather than editing this one.
// lufs: integrated loudness at the default level (ITU-R BS.1770), lowShare: share of energy below 150 Hz.

export interface VersionData { lufs: number; lowShare: number }

export const SOUND_DATA_V1: Record<string, VersionData> = {
  'brown': { lufs: -22.14, lowShare: 0.439 },
  'red': { lufs: -23.32, lowShare: 0.674 },
  'pink': { lufs: -22.3, lowShare: 0.262 },
  'white': { lufs: -31.36, lowShare: 0.005 },
  'tone432': { lufs: -29.15, lowShare: 0 },
  'tone528': { lufs: -29.69, lowShare: 0 },
  'fan': { lufs: -22.74, lowShare: 0.762 },
  'rain': { lufs: -23.08, lowShare: 0.087 },
  'rain.b': { lufs: -23.15, lowShare: 0.015 },
  'ocean': { lufs: -23.72, lowShare: 0.046 },
  'wind': { lufs: -25.61, lowShare: 0.397 },
  'stream': { lufs: -28.23, lowShare: 0.043 },
  'fire': { lufs: -23.5, lowShare: 0.727 },
  'night': { lufs: -27.66, lowShare: 0 },
  'focus': { lufs: -23.09, lowShare: 0.64 },
  'zen': { lufs: -23.04, lowShare: 0.713 },
};
