// Generated by scripts/blend-lab/measure.mjs. Do not edit by hand.
//
// Auto-Blend v2 per-version measurements, frozen once shipped: a saved Mix with blend v2 must always plan the
// same, so a later re-measure goes into a new table for a new rule version rather than editing this one.
// lufs: integrated loudness at the default level (ITU-R BS.1770), lowShare: share of energy below 150 Hz,
// motion: recordings only, the spread of the slow level (waves, gusts) in dB, which picks who sets the pace.

import type { VersionData } from './blend-data.js';

export const SOUND_DATA_V2: Record<string, VersionData & { motion?: number }> = {
  'brown': { lufs: -22.14, lowShare: 0.439 },
  'red': { lufs: -23.32, lowShare: 0.674 },
  'pink': { lufs: -22.3, lowShare: 0.262 },
  'white': { lufs: -31.36, lowShare: 0.005 },
  'tone432': { lufs: -29.15, lowShare: 0 },
  'tone528': { lufs: -29.69, lowShare: 0 },
  'fan': { lufs: -22.74, lowShare: 0.762 },
  'rain': { lufs: -23.08, lowShare: 0.087, motion: 0.77 },
  'rain.b': { lufs: -23.15, lowShare: 0.015, motion: 0.68 },
  'ocean': { lufs: -23.72, lowShare: 0.047, motion: 5.96 },
  'wind': { lufs: -25.61, lowShare: 0.444, motion: 2.34 },
  'wind.c': { lufs: -25.66, lowShare: 0.509, motion: 1.79 },
  'wind.d': { lufs: -25.64, lowShare: 0.517, motion: 1.74 },
  'wind.e': { lufs: -25.61, lowShare: 0.393, motion: 1.54 },
  'stream': { lufs: -28.23, lowShare: 0.043, motion: 3.08 },
  'stream.c': { lufs: -28.24, lowShare: 0.036, motion: 1.34 },
  'stream.d': { lufs: -28.26, lowShare: 0.036, motion: 0.91 },
  'stream.e': { lufs: -28.2, lowShare: 0.019, motion: 0.38 },
  'fire': { lufs: -23.5, lowShare: 0.727, motion: 1.28 },
  'night': { lufs: -27.66, lowShare: 0, motion: 1.11 },
  'focus': { lufs: -23.09, lowShare: 0.64 },
  'zen': { lufs: -23.04, lowShare: 0.713 },
};
