// Generated by scripts/blend-lab/measure.mjs. Do not edit by hand.
//
// Auto-Blend v3 per-version measurements, frozen once shipped: a saved Mix with blend v3 must always plan the
// same, so a later re-measure goes into a new table for a new rule version rather than editing this one.
// lufs: integrated loudness at the default level (ITU-R BS.1770), lowShare: share of energy below 150 Hz,
// motion: recordings only, the spread of the slow level (waves, gusts) in dB, which picks who sets the pace.

import type { VersionData } from './blend-data.js';

export const SOUND_DATA_V3: Record<string, VersionData & { motion?: number }> = {
  'brown': { lufs: -25.16, lowShare: 0.439 },
  'red': { lufs: -26.31, lowShare: 0.674 },
  'pink': { lufs: -25.23, lowShare: 0.262 },
  'white': { lufs: -34.13, lowShare: 0.005 },
  'tone432': { lufs: -31.92, lowShare: 0 },
  'tone528': { lufs: -32.47, lowShare: 0 },
  'fan': { lufs: -25.67, lowShare: 0.762 },
  'rain': { lufs: -26.58, lowShare: 0.086, motion: 1.77 },
  'rain.b': { lufs: -26, lowShare: 0.015, motion: 2 },
  'ocean': { lufs: -36.53, lowShare: 0.408, motion: 13.4 },
  'ocean.f': { lufs: -26.63, lowShare: 0.047, motion: 11.87 },
  'wind': { lufs: -34.67, lowShare: 0.803, motion: 5.25 },
  'wind.f': { lufs: -33.12, lowShare: 0.489, motion: 6.75 },
  'wind.c': { lufs: -28.54, lowShare: 0.423, motion: 7.44 },
  'wind.d': { lufs: -31.29, lowShare: 0.501, motion: 5.55 },
  'wind.e': { lufs: -29.42, lowShare: 0.369, motion: 5.16 },
  'stream': { lufs: -51.05, lowShare: 0.5, motion: 3.37 },
  'stream.f': { lufs: -31.18, lowShare: 0.039, motion: 3.85 },
  'stream.c': { lufs: -31.17, lowShare: 0.032, motion: 1.41 },
  'stream.d': { lufs: -31.18, lowShare: 0.036, motion: 0.97 },
  'fire': { lufs: -38.21, lowShare: 0.083, motion: 11.98 },
  'fire.f': { lufs: -39.62, lowShare: 0.719, motion: 1.48 },
  'night': { lufs: -45.56, lowShare: 0.504, motion: 2.94 },
  'night.f': { lufs: -35.57, lowShare: 0, motion: 2.01 },
  'gulls': { lufs: -42.94, lowShare: 0.024, motion: 3.36 },
  'focus': { lufs: -26.08, lowShare: 0.64 },
  'zen': { lufs: -26.03, lowShare: 0.713 },
};
